package zzbot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Unit test for the {@link Deadlines} class.
 * This test suite verifies the functionality of the Deadlines class,
 * including proper description formatting for both incomplete and completed tasks.
 */
class DeadlinesTest {

    private Deadlines deadline1;
    private Deadlines deadline2;

    /**
     * Initializes the {@link Deadlines} instances before each test.
     * <p>
     * deadline1: Represents an incomplete task with a due date.
     * deadline2: Represents a completed task with a due date.
     * </p>
     */
    @BeforeEach
    void setUp() {
        // Initialize Deadlines instances for testing
        deadline1 = new Deadlines("Submit assignment", LocalDate.of(2024, 9, 30));
        deadline2 = new Deadlines("Submit project", true, LocalDate.of(2024, 10, 15));
    }

    /**
     * Tests the {@link Deadlines#describe()} method.
     * <p>
     * Ensures that the description string generated by the describe method matches
     * the expected format for both incomplete and completed deadlines.
     * </p>
     */
    @Test
    void testDescribe() {

        String expectedDescription1 = "[D][ ] Submit assignment (by: Sep 30 2024)";
        String expectedDescription2 = "[D][X] Submit project (by: Oct 15 2024)";

        assertEquals(expectedDescription1, deadline1.describe(), "Description should match the expected format for incomplete task");
        assertEquals(expectedDescription2, deadline2.describe(), "Description should match the expected format for completed task");
    }
}
